### ISSUE TITLE
 t c-curl vs t-retracted c-curl vs c c-curl

### ISSUE THREAD

**Issue by bambooforest** [phoible/phoible#89]
Before I update, I did a quick and dirty query

select LanguageCode, Source, Phoneme from phoible-phoneme-level-no-trump.tsv where Phoneme like '%ɕ%'

and get this (minus the lots of rows that return simply <ɕ>:

phl ph tɕ
pol ph tɕ
aka gm tɕ
mij gm tɕ
cav ph tɕ
jya ph tɕ
pbr gm tɕ
tsj ph tɕ
kig ph tɕ
cmn ph tɕ
hrv ph tɕ
afu gm tɕ
kxm ph tɕ
buu gm tɕ
bdh gm tɕ
kmw aa tɕ
aja gm tɕ
bod ph tɕ
afo gm tɕ
lno gm tɕ
knc aa tɕ
krs aa tɕ
iri gm tɕ
pww ph tɕ
aka gm tɕᶣ
afu gm tɕᶣ
cko gm ɕᶣ
aka gm ɕᶣ
bod ph tɕʰ
kxm ph tɕʰ
cmn ph tɕʰ
jya ph tɕʰ
tsj ph tɕʰ
pww ph tɕʰ
knn upsid cɕ
cnh upsid cɕ
tel upsid cɕ
teh upsid cɕ
nbf upsid cɕ
gio upsid cɕ
brv upsid cɕ
nbf upsid cɕʰ
gio upsid cɕʰ
cnh upsid cɕʰ
gio upsid ɲcɕ
iri gm tɕʷ
kjq upsid ɕʼ
snk aa ɕː
teh upsid cɕʼ

UPSID could be updated as suggested:

cɕʰ
cɕ
cɕʼ
ɲcɕ

t̠ɕʰ
t̠ɕ
t̠ɕʼ
ɲt̠ɕ

But anything else that all be retracted and the rows updated in the features file?

**Comment by drammock** [comment]
Check out this excerpt from the aggregation script:
```r
root.dir <- file.path("..", "..")
data.dir <- file.path(root.dir, "data")
upsid.ipa.path <- file.path(data.dir, "UPSID", "UPSID_IPA_correspondences.tsv")
upsid.ipa <- read.delim(upsid.ipa.path, na.strings="", quote="", stringsAsFactors=FALSE)
# this next bit is new
upsid.ipa[with(upsid.ipa, pal & (fric | ejfric | aff | ejaff)), c("Phoneme", "alv", "palalv", "ret", "pal", "sib")]
```
What we see is inconsistency in how we've translated UPSID features `pal` and `sib`. I'll fix this in UPSID first, then see what is left with regard to consistency with the rest of the database.  What I recall now is that:

1. we decided `tɕ` did not need a retraction mark because it was a simultaneous alveolar + palatal constriction, and
2. in UPSID, we *intended* to interpret the feature combination `+pal +sib` to mean `ɕ` and `+pal -sib` to mean `ç` because there was no other way to make sense of it.

Please chime in if you remember it differently or have anything to add.
The "palatal sibilant affricate" in UPSID simply can't be done

**Comment by bambooforest** [comment]
I tried to keep all decisions regarding UPSID in the UPSID-IPA
correspondences. I found a document I'll send you by email.

**Comment by drammock** [comment]
alas, that document does little if anything to help. From page 17:

> Palato-alveolar (pal_al): Palato-alveolar and alveo-palatal are not distinguished.
> Palatal (pal): [no clarifying remarks are given]

Looking again at the UPSID character codes, they consistently use `c` for "palatal stop", `C` for "palatal fricative", and `C,` for "palatal sibilant fricative" so I think we were right to interpret `C,` as `ɕ`. Since palatal sibilant fricatives and affricates are described in UPSID as `-alveolar` it is hard to justify using `t` as the symbol for the stop portion (and similarly `n` for any prenasalized portion), but that is the choice that would be most consistent with the rest of the database.  Ultimately I think I'm going to have to assume that UPSID labeled `ɕ` as `-alv` simply because they didn't allow multiple place features to be true for a single segment.  Therefore, unless you object, @bambooforest, I will change all UPSID `cɕ` to `tɕ`.

**Comment by bambooforest** [comment]
sgtm
